/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React, { useEffect, useRef } from 'react';
import { Download, CheckCircle2, Code, Package } from 'lucide-react';
import { GeneratedSvg } from '../types';
import { generateIconPackage } from '../utils/iconPackage';

interface SvgPreviewProps {
  data: GeneratedSvg | null;
}

export const SvgPreview: React.FC<SvgPreviewProps> = ({ data }) => {
  const [copied, setCopied] = React.useState(false);
  const [generatingPackage, setGeneratingPackage] = React.useState(false);
  const [showCode, setShowCode] = React.useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // Reset copied state when data changes
  useEffect(() => {
    setCopied(false);
    setShowCode(false);
  }, [data]);

  if (!data) return null;

  const handleDownload = () => {
    const blob = new Blob([data.content], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `vectorcraft-${data.id}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(data.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleToggleCode = () => {
    if (showCode) {
      navigator.clipboard.writeText(data.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
    setShowCode(!showCode);
  };

  const handleDownloadPackage = async () => {
    if (!data) return;
    
    setGeneratingPackage(true);
    try {
      const packageBlob = await generateIconPackage(data.content, data.prompt);
      const url = URL.createObjectURL(packageBlob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `icon-package-${data.id}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to generate icon package:', error);
    } finally {
      setGeneratingPackage(false);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-12 px-4 animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="bg-zinc-900/80 backdrop-blur border border-white/10 rounded-2xl overflow-hidden shadow-2xl">
        {/* Toolbar */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-white/10 bg-zinc-900/50">
          <h3 className="text-sm font-medium text-zinc-300 truncate max-w-[150px] sm:max-w-xs">
           <span className="text-zinc-500">"{data.prompt}"</span>
          </h3>
          <div className="flex gap-2">
            <button
              onClick={handleToggleCode}
              className="p-2 text-zinc-400 hover:text-white hover:bg-white/10 rounded-lg transition-colors group relative"
              title={showCode ? "Copy SVG Code" : "View SVG Code"}
            >
              {copied ? <CheckCircle2 className="w-5 h-5 text-green-400" /> : <Code className="w-5 h-5" />}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-zinc-900 bg-white rounded-lg hover:bg-zinc-200 transition-colors"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">SVG</span>
            </button>
            <button
              onClick={handleDownloadPackage}
              disabled={generatingPackage}
              className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <Package className="w-4 h-4" />
              <span className="hidden sm:inline">{generatingPackage ? 'Generating...' : 'Icon Pack'}</span>
            </button>
          </div>
        </div>

        {/* Canvas Area */}
        <div className="p-8 flex items-center justify-center bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] bg-zinc-950/50 min-h-[400px]">
          {showCode ? (
            <div className="w-full max-w-4xl">
              <pre className="bg-zinc-900 border border-zinc-700 rounded-lg p-4 text-xs text-zinc-300 overflow-auto max-h-96 whitespace-pre-wrap">
                {data.content}
              </pre>
            </div>
          ) : (
            /* 
             Using dangerouslySetInnerHTML is intentional here as the content is generated by the LLM for the purpose of display.
           */
            <div 
              ref={containerRef}
              className="w-full max-w-[512px] h-auto transition-all duration-500 transform hover:scale-[1.02] filter drop-shadow-2xl"
              dangerouslySetInnerHTML={{ __html: data.content }} 
            />
          )}
        </div>
        
        {/* Metadata Footer */}
        <div className="px-4 py-2 bg-zinc-950 border-t border-white/5 flex justify-between text-xs text-zinc-600">
          <span>Gemini 3 Pro</span>
        </div>
      </div>
    </div>
  );
};
